# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.


  # This Vagrantfile is specifically for the webmaker suite of apps, cloned from https://github.com/mozilla/webmaker-suite
  # This is in beta, please submit
  # bugs via webmaker :: devops, or email jp@mozillafoundation.org
  config.vm.box = "webmakersuite"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://stuff.webmaker.org/devtools/webmakersuite.box"

  # Create forwarded port mappings
  # Webmaker apps have the following port assignments/urls
  # which are opened up to your local workstation by the
  # following stanzas

  # Configure mongo and elasticsearch port forwards

  config.vm.network :forwarded_port, guest: 27017, host: 27017
  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 9300, host: 9300

  # Configure forwarded ports for the following apps
  # http://localhost:3000 - login.webmaker.org
  # http://localhost:3500 - thimble.webmaker.org
  # http://localhost:5000 - makeapi
  # http://localhost:5050 - htmlsanitizer.org
  # http://localhost:7777 - webmaker.org
  # http://localhost:8888 - popcorn.webmaker.org
  # http://localhost:12416 - goggles.webmaker.org

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 3500, host: 3500
  config.vm.network :forwarded_port, guest: 5000, host: 5000
  config.vm.network :forwarded_port, guest: 5050, host: 5050
  config.vm.network :forwarded_port, guest: 7777, host: 7777
  config.vm.network :forwarded_port, guest: 8888, host: 8888
  config.vm.network :forwarded_port, guest: 12416, host: 12416

end
